"""
Django settings for provesi_wms project.
Generated by 'django-admin startproject' using Django 5.1.2.
"""

from pathlib import Path
import os

# ==== Paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ==== Seguridad / Debug (solo dev)
SECRET_KEY = 'django-insecure-*5p2t&g88*0x1vobm^1d(fw3*0-s(h2v(i5#$)!qy7s3)+fn1d'
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ==== Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.orders.apps.OrdersConfig',  # registra señales si las tienes
    'inventario',
]

# ==== Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'provesi_wms.urls'

# ==== Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # agrega rutas si usas plantillas fuera de los apps
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'provesi_wms.wsgi.application'

# ==== Base de datos (PostgreSQL local)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "provesi_wms"),
        "USER": os.getenv("DB_USER", "provesi"),      # cambia a tu user local si usas la opción B
        "PASSWORD": os.getenv("DB_PASSWORD", "1234"),  # vacío si usas la opción B
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,
        "ATOMIC_REQUESTS": False,
    }
}

# ==== Passwords
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==== I18N / TZ
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==== Static
STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==== Cache (Redis con fallback a memoria para desarrollo)
USE_LOC_MEM_CACHE = os.getenv("USE_LOC_MEM_CACHE") == "1"   # fuerza LocMem si no quieres correr Redis
CACHE_TTL_SECONDS = int(os.getenv("CACHE_TTL_SECONDS", "300"))

if USE_LOC_MEM_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "provesi-local",
            "TIMEOUT": CACHE_TTL_SECONDS,
            "KEY_PREFIX": "provesi",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
                # Evita que caiga toda la app si Redis no responde (útil en dev)
                "IGNORE_EXCEPTIONS": True,
                "CONNECTION_POOL_KWARGS": {"max_connections": 50, "retry_on_timeout": True},
            },
            "TIMEOUT": CACHE_TTL_SECONDS,
            "KEY_PREFIX": "provesi",
        }
    }

# (Opcional) sesiones en caché para endpoints anónimos
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"
